### ISSUE TITLE
Provide binaries for various platforms

### ISSUE THREAD

**Issue by rakshazi** [nachoparker/dutree#3]
Hello!
Please, provide binaries of dutree for various platforms. `linux 64bit` is a good starting point.

**Comment by nachoparker** [comment]
quite easy to just do `cargo install dutree`... in any case not a bad idea. 

Pretty busy right now with other projects, but help is welcome

**Comment by rakshazi** [comment]
Yep, but not for people not familiar with Rust :)
So, I should setup full rust env just for one small tool, it's not very usable...

**Comment by nachoparker** [comment]
;D
