### ISSUE TITLE
Building from source: errors

### ISSUE THREAD

**Issue by kurdtpage** [nachoparker/dutree#31]
I am using version [0.2.15](https://github.com/nachoparker/dutree/archive/v0.2.15.zip)
Installed latest version of rust for ubuntu (`sudo apt-get update && sudo apt-get install rustc`)
```
kurdtpage@ubuntu:~/dutree-0.2.15/src$ rustc main.rs
error[E0463]: can't find crate for `dutree`
  --> main.rs:37:1
   |
37 | extern crate dutree;
   | ^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
```

**Comment by crypticspawn** [comment]
cargo install dutree


What I did on ubuntu:
`:~/repositories/dutree$ cargo install dutree
    Updating crates.io index
  Downloaded dutree v0.2.16
  Downloaded 1 crate (638.0 KB) in 3.35s
  Installing dutree v0.2.16
  Downloaded terminal_size v0.1.13
  Downloaded signal-hook-registry v1.2.1
  Downloaded unicode-width v0.1.8
  Downloaded libc v0.2.79
   Compiling libc v0.2.79
   Compiling memchr v2.3.3
   Compiling lazy_static v1.4.0
   Compiling arc-swap v0.4.7
   Compiling regex-syntax v0.6.18
   Compiling unicode-width v0.1.8
   Compiling unicode-segmentation v1.6.0
   Compiling thread_local v1.0.1
   Compiling getopts v0.2.21
   Compiling aho-corasick v0.7.13
   Compiling signal-hook-registry v1.2.1
   Compiling terminal_size v0.1.13
   Compiling signal-hook v0.1.16
   Compiling regex v1.3.9
   Compiling dutree v0.2.16
    Finished release [optimized] target(s) in 26.52s
  Installing /home/niterain/.cargo/bin/dutree
   Installed package `dutree v0.2.16` (executable `dutree`)
`
