### ISSUE TITLE
Unable to build with --locked due to missing Cargo.lock

### ISSUE THREAD

**Issue by wezm** [nachoparker/dutree#35]
https://github.com/nachoparker/dutree/commit/603b9fea2f1e2a2af06b9f6812dddde231a2fcc0 removed the `Cargo.lock` file. This means it's not possible to build with the `--locked` argument with cargo. This is preferred when [building packages](https://aur.archlinux.org/packages/dutree/) from tagged releases to ensure that the exactly the same version of dependencies are used to ensure builds are reproducible. For binary projects it is recommended to commit the lock file: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

Would it be possible to include the lock file in future releases?

**Comment by nachoparker** [comment]
True, shouldn't have been removed.

Added it back.

Thanks!

**Comment by wezm** [comment]
Awesome, thank you.

**Comment by SpineEyE** [comment]
Can you please release a version with it? Otherwise the package can't be installed from the AUR.

**Comment by nachoparker** [comment]
@SpineEyE what do you mean? latest `master` has the file

**Comment by wezm** [comment]
The last tagged release doesn't include that commit though.

**Comment by nachoparker** [comment]
I see, does the AUR package use `cargo install`? or does in use the HEAD of `master`, or how does it work?

**Comment by nachoparker** [comment]
I see, it does `cargo build --release --locked`

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dutree

**Comment by nachoparker** [comment]
Let's create 0.2.16 then

**Comment by lmartinez-mirror** [comment]
The 0.16.0 tarball still doesn't have the Cargo.lock file needed to compile according to Arch's [Rust package guidelines](https://wiki.archlinux.org/index.php/Rust_package_guidelines#Building). I've since taken over ownership of the AUR package, and only recently noticed this. If someone could add it whenever convenient, I'd appreciate it!

**Comment by nachoparker** [comment]
@lmartinez-mirror I guess it never was pushed. Just pushed 0.2.17

Thanks for the AUR package!

**Comment by lmartinez-mirror** [comment]
@nachoparker Thank you for the update! However, it looks like the Cargo.lock file pushed is for 0.2.16, not 0.2.17. I could patch in the correct version on my end, but I don't think lock files are supposed to be edited directly. Could you please fix this whenever you get the chance? Thanks!
